config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controller:{
    sessions: 'sessions'
  }

  root 'home#index'

  resources :users do
    resources :services, shallow: true
    resources :uploads, shallow: true
  end

  match '/users/services', to:'services#create',  via: 'POST'
  match '/users/services/search', to:'home#search',  via: 'GET'
  match '/users/services', to:'services#create',  via: 'POST'
  

end

app/models/service.rb
class Service < ActiveRecord::Base
	belongs_to :user
	has_many :uploads
end

app/models/upload.rb
class Upload < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :services
  has_many :uploads


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  

  
  def index
  	if user_signed_in?
  		@files = current_user.uploads
  	end

  end

  def recent

  end

  def search

  end  
  



end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def create
  	Service.create(:user_id => params[:user_id], :service_id => params[:service_id], :service_name => params[:service_name] ,:folder_id => params[:folder_id])
    render :nothing => true
  end


  

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  def create
    Upload.create(:user_id => params[:user_id], :gservice => params[:gservice], :dservice => params[:dservice], :gfid => params[:gfid], :dfid => params[:dfid] ,:fname => params[:fname], :mimetype => params[:mimetype])
    render :nothing => true
  end

  def destroy
    target = Upload.find( params[:id] )
    Upload.destroy(target)
    render :nothing => true   
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
require 'json'
module ServicesHelper
	def KloudlessList(service_id, folder_id)
		
	    uri = URI("https://api.kloudless.com:443/v0/accounts/"+service_id+"/folders/"+folder_id+"/contents/")

		http = Net::HTTP.new(uri.host, uri.port)
		http.use_ssl = true

		request = Net::HTTP::Get.new(uri.request_uri)
		puts uri.request_uri
		request["Authorization"] = "ApiKey CbdAL_JeRmFRx0ZuxP1wLAzbVv5IeyrVXtdJ1cigadzDOAin"

		response = http.request(request)

		jres = JSON.parse(response.body)

		#type =  jres.class
		#return type

		return jres["objects"]
		#return response.body["objects"][4]
	end



	def recentList(service_id)

	end


	def searchFile(service_id, query)
		uri = URI("https://api.kloudless.com:443/v0/accounts/"+ service_id + "/search/?q="+query)

		http = Net::HTTP.new(uri.host, uri.port)
		http.use_ssl = true

		request = Net::HTTP::Get.new(uri.request_uri)
		puts uri.request_uri
		request["Authorization"] = "ApiKey CbdAL_JeRmFRx0ZuxP1wLAzbVv5IeyrVXtdJ1cigadzDOAin"

		response = http.request(request)

		jres = JSON.parse(response.body)

		#type =  jres.class
		#return type

		return jres["objects"]

	end

end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/home/index.html.erb
<% $count = 0 %>

<% if user_signed_in? %>
  <% if current_user.services.count == 2 %>
    <% @Gservice = current_user.services.where( :service_name => 'gdrive').first()  %>
    <% @Dservice = current_user.services.where( :service_name => 'dropbox').first() %>
  <!-- search_field -->
    <div class="col-md-6 col-md-offset-3">
		<%= bootstrap_form_tag url: users_services_search_url, method: :GET do |f| %>
		  <%=  f.text_field :search, append: link_to("Go",'#', class: "btn btn-success" , id: 'submit') %>
		  <%= f.submit "Go", class: :done %>
		<% end %>
	</div>

    
    <div class="col-md-6 col-md-offset-3"> 
		<form id="yzu" method="get" enctype="multipart/form-data" class="ugly">
		  <div class="form-group">
		    <label for="exampleInputFile">File Upload</label>
		    <input type="file" id="file" name="file" class="parameter">
		  </div>
		  <button type="submit" class="btn btn-default up" id = "yzu2" data-uid= '<%= current_user.id %>' data-gid= '<%= @Gservice.service_id  %>' data-did= '<%= @Dservice.service_id  %>' data-gfolder='<%= @Gservice.folder_id %>' data-dfolder='<%= @Dservice.folder_id %>'>Submit</button>
		</form>
	</div>
     
   

    <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-5">
          </div>
        </div>
    
      

            <% @files.each do |file| %>
    
              <% if $count.to_i() % 3 == 0%>
                <div class="row">
              <% end%>
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="X.png" style="width:150px;height:auto;" alt="...">
                    <div class="caption">
                        <h3 style="word-break:break-word;"><%= file.fname %></h3>
                        <p> Modified: <%= file.created_at %></p>
                        <p> Type: <%= file.mimetype %></p>
                        <p>
                          <a href="#" class="btn btn-primary arthur" role="button" data-gid='<%= @Gservice.service_id %>' data-did='<%= @Dservice.service_id %>' data-gfileid='<%= file.gfid %>' data-dfileid='<%= file.dfid %>' data-filename='<%= file.fname %>'  >Downloads</a> 
                          <a href="#" class="btn btn-danger jamie" role="button" data-id='<%= file.id %>'
                           data-gid='<%= @Gservice.service_id %>' data-did='<%= @Dservice.service_id %>' data-gfileid='<%= file.gfid %>' data-dfileid='<%= file.dfid %>' >Destroy!</a>
                        </p>
                    </div>
                </div>
              </div>
              <% if $count.to_i() % 3 == 2%>
                  </div>
              <% end %>
              <% $count += 1 %>
            <% end %>		
            
            <% if $count == 0 %>
            <br><br><br>
            <div class="jumbotron ">
		      <h2>You nerver upload any file from X-cloud service</h2>
		    </div>
            <% end %>
    <!-- </div> -->
	</div>	

  <% else %>
    <div class="jumbotron">
      <h2>You don't bind any cloudStorage now, Please press Auth button to bind.</h2>
    </div>  
  <% end %>
<% else %>
    <div class="jumbotron">
    <h1>Hello, WElcome!</h1>
    <p>.....Login first!</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>
<% end %>





<script>

$(function() {
  $(".ugly").hide();

  $(".done").hide(); 
  
  $( "#submit" ).click(function() {
  	 $(".done" ).click();
  });

  $("#fileupload").click(function(){
  	 $("#file").click();

  });

  $("#file").on("change",function(){
  	 $(".up").click();

  });


});



    var e = document.getElementById("auth-button");

    // You can also use jQuery:
    e = $('#auth-button');

    Kloudless.authenticator(e, {
        'client_id': 'qNxuBpHOy8YUkhq5UaxNCsjGtZW1oC_4922O6YqqFDHSIzat'    
    }, function (result) {
        if (result.error) {
            console.error('An error occurred:', result.error);
            return;
        }
        console.log('Yay! I now have a newly authenticated', result.account.service,
            'account with ID', result.account.id);
           
  
    <% if user_signed_in? %>
        $user_id = <%= current_user.id %>; 
    <% end %>
    $service_id = result.account.id;
    $service_name = result.account.service;


    $.ajax({
        url: "https://api.kloudless.com:443/v0/accounts/" + $service_id + "/folders/?conflict_if_exists=true",
        beforeSend: function(xhr) {
            xhr.setRequestHeader('Authorization', 'ApiKey CbdAL_JeRmFRx0ZuxP1wLAzbVv5IeyrVXtdJ1cigadzDOAin');
        },
        data: JSON.stringify({
            "name": "X-Cloud",
            "parent_id": "root"
        }),
        contentType: "application/json",
        type: "POST",
        dataType: "JSON"
    }).done(function(req) {
        $folder_id = req["id"];

        $.ajax({
            url: "/users/services",
            data: {
                user_id: $user_id,
                service_id: $service_id,
                service_name: $service_name,
                folder_id: $folder_id
            },
            type: "POST"
        }).done(function(req){
            window.location = "/";
          });
    });

   });


</script>

app/views/home/search.html.erb
<% $count = 0 %>

<script type="text/javascript">
	$(function() {
	  $(".done").hide(); 
	  
	  $( "#submit" ).click(function() {
	  	 $( ".done" ).click();
	  });
	});
</script>


<% if user_signed_in? %>
  <% if current_user.services.exists? %>
       <!--  <form class="form-horizontal" >
            <div class="form-group">
            	<div class="col-md-6 col-md-offset-3">
                  <input type="text" class="form-control" placeholder="Search" name="query">
                </div>
                  <%#= link_to 'submit', '/users/services/search', :class => 'btn btn-success' %>
            </div>
        </form> -->
    <div class="col-md-6 col-md-offset-3">
		<%= bootstrap_form_tag url: users_services_search_url, method: :GET do |f| %>
		  <%=  f.text_field :search, append: link_to("Go",'#', class: "btn btn-success" , id: 'submit') %>
		  <%= f.submit "Go", class: :done %>
		<% end %>
	</div>

    <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-5">
          </div>
        </div>
        <% current_user.services.each do |service| %>
            <%#=  service.service_name %>
          <% files = searchFile(service.service_id, params[:search] ) %>

            
            <% files.each do |file| %>
              <% if $count.to_i() % 3 == 0%>
                <div class="row">
              <% end%>
              <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <img src="/X.png" style="width:150px;height:auto;" alt="...">
                    <div class="caption">
                        <h3 style="word-break:break-word;"><%= file["name"] %></h3>
                        <p> Modified: <%= file["modified"] %></p>
                        <p> Type: <%= file["mime_type"] %></p>
                        <p><a href="#" class="btn btn-primary" role="button">Download</a> <a href="#" class="btn btn-danger" role="button">Delete</a></p>
                    </div>
                </div>
              </div>
              <%  if $count.to_i() % 3 == 2%>
                </div>
              <%end%>
              <% $count += 1 %>
            <%end%>		
        <%end%>
        <% if $count == 0 %>
           <br><br><br>
           <div class="jumbotron ">
		      <h2>No such file in your cloudStorage</h2>
		   </div>
        <% end %>
    <!-- </div> -->
	</div>
	<%end%>
<%end%>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloudStorage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag '//static-cdn.kloudless.com/p/platform/sdk/kloudless.authenticator.js' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2014-11-29/FileSaver.min.js' %>
  <%= javascript_include_tag '//cdnjs.cloudflare.com/ajax/libs/async/0.9.0/async.js' %>
  <%= csrf_meta_tags %>
  <%= render 'shared/nav' %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">X-CloudStorage</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <% if user_signed_in? %>
                <li class="active">
                    <a href="#" id="auth-button">Auth</a>
                </li>
                <li>
                    <a href="#" id="fileupload">Upload</a>
                </li>
                <%end%>
            </ul>
          
            <ul class="nav navbar-nav navbar-right">
                <% if !user_signed_in? %>  
                <li><%= link_to 'Sign_In', new_user_session_url %></li>  
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
                </li>
                <% else %>
                <li><%= link_to 'Log out', destroy_user_session_url ,:method => :delete %></li>
                <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>